Repository Ibotta/sk-dist, pull requests merged in 2019-09, with the labels that each got.

#9 Remove errant text from PR template
  PULL_REQUEST_TEMPLATE.md
Labels: good first issue, help wanted

#5 Add `DistFeatureEliminator` class and `select` module
  examples/eliminate/README.md
  examples/eliminate/basic_usage.py
  examples/eliminate/covtype.py
  skdist/__init__.py
  skdist/distribute/__init__.py
  skdist/distribute/eliminate.py
  skdist/distribute/tests/test_eliminate.py
Labels: help wanted

#10 Pyspark testing suite
  .travis.yml
  README.rst
  setup.py
  skdist/__init__.py
  skdist/tests/test_spark.py
Labels: enhancement, help wanted
